### ISSUE TITLE
ERROR: failed to solve: process "/bin/sh -c mv /usr/games/.config/user-dirs.conf /etc/xdg/user-dirs.defaults" did not complete successfully"

### ISSUE THREAD

**Issue by gdragon-git** [nuxy/docker-steamcmd-wine#3] opened 2023-05-18 22:47 UTC
Getting the following error. System: Debian 11 bullseye LXC container for ProxMox 7.4-3 (CT debian-11-standard_11.6-1_amd64) running on Debian 11 host.

 ERROR [16/17] RUN mv /usr/games/.config/user-dirs.conf /etc/xdg/user-dirs.defaults                                                                                                                        
------
 > [16/17] RUN mv /usr/games/.config/user-dirs.conf /etc/xdg/user-dirs.defaults:
#0 0.391 mv: cannot move '/usr/games/.config/user-dirs.conf' to a subdirectory of itself, '/etc/xdg/user-dirs.defaults'

Full output of build attempt:
```txt
root@portainer-lxc:~/vrising-docker-steamcmd-wine# docker build -t vrising-docker . --build-arg APPID=1829350 --build-arg RUNCMD="-persistentDataPath /usr/games/files"

Start Build
[+] Building 91.8s (20/21)                                                                                                                                                                                         
 => [internal] load .dockerignore                                                                                                                                                                             0.0s
 => => transferring context: 2B                                                                                                                                                                               0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                          0.0s
 => => transferring dockerfile: 1.76kB                                                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/scottyhardy/docker-wine:latest                                                                                                                                     1.3s
 => [ 1/17] FROM docker.io/scottyhardy/docker-wine@sha256:d8e4475a7a58660221097be4bb6f886373fac94a360a2d4e1f5ab4d2b971d31e                                                                                   28.4s
 => => resolve docker.io/scottyhardy/docker-wine@sha256:d8e4475a7a58660221097be4bb6f886373fac94a360a2d4e1f5ab4d2b971d31e                                                                                      0.0s
 => => sha256:f514df9e2066d99e9258609e5ccfde2214b6b74d113bd94692b9b53c20638cca 2.77kB / 2.77kB                                                                                                                0.0s
 => => sha256:4c67ac859a6ba5a62f306445b5632ea6c6b31edd2cfe00ac32914906aa41bfe0 7.35kB / 7.35kB                                                                                                                0.0s
 => => sha256:8142be1d7640b2609c749c8b33689becd1b9cf7b7968434c9422ff14987fee95 272.13MB / 272.13MB                                                                                                            5.1s
 => => sha256:2691a0c36c42b91e61af585632f4933c5f1769fc4fb26b88924e3ad754c333c7 863.68kB / 863.68kB                                                                                                            0.6s
 => => sha256:ca1778b6935686ad781c27472c4668fc61ec3aeb85494f72deb1921892b9d39e 27.50MB / 27.50MB                                                                                                              0.4s
 => => sha256:d8e4475a7a58660221097be4bb6f886373fac94a360a2d4e1f5ab4d2b971d31e 856B / 856B                                                                                                                    0.0s
 => => extracting sha256:ca1778b6935686ad781c27472c4668fc61ec3aeb85494f72deb1921892b9d39e                                                                                                                     0.4s
 => => sha256:f365d802bc44a6ad12882eb4d65c923dc581896d9211598f0a6fcc13dd415e0e 75.21kB / 75.21kB                                                                                                              0.6s
 => => sha256:1610a2a20e2e6edc88de59c552431c6c5f4c952f0b5f3860fd4bf36a84ba4bed 396B / 396B                                                                                                                    0.8s
 => => sha256:253f4d9d62d1dcde17221764cad8a6730a4e65caf09e086e53b9154ec95967f5 65.02MB / 65.02MB                                                                                                              2.1s
 => => sha256:eb8a848ba9121c881d4cd0f77e97b58319b20058c83693d1a0d197b706d1a111 579.40MB / 579.40MB                                                                                                           10.9s
 => => sha256:e5da18124cc8ae8db4caa90b5f052116fa68b6e058c717259cb5252d4addd046 171.62kB / 171.62kB                                                                                                            2.3s
 => => sha256:515f8cd27a372807a993910898cdc309c80ba205e8085716d578257661e59074 827B / 827B                                                                                                                    2.5s
 => => sha256:84c35afd7ff237f4273e5c035d333058b4cd702425363abc1d8d013f5ac92727 196.78MB / 196.78MB                                                                                                            8.0s
 => => sha256:aed635b11e9aa855e41fa90d660ff1a079d37e66edf02fff34606661856ea1dd 863.47kB / 863.47kB                                                                                                            5.2s
 => => extracting sha256:8142be1d7640b2609c749c8b33689becd1b9cf7b7968434c9422ff14987fee95                                                                                                                     5.5s
 => => sha256:e5e90ebfb41ba0be3922b7e3696711cc410ec6533d1f91a7aebf65dc0efccb14 328B / 328B                                                                                                                    5.4s
 => => sha256:162c6388688c70f96d2b3682d1d2f21e72891283f1a38a78267d8533d51cd557 1.90kB / 1.90kB                                                                                                                5.7s
 => => extracting sha256:2691a0c36c42b91e61af585632f4933c5f1769fc4fb26b88924e3ad754c333c7                                                                                                                     0.0s
 => => extracting sha256:f365d802bc44a6ad12882eb4d65c923dc581896d9211598f0a6fcc13dd415e0e                                                                                                                     0.0s
 => => extracting sha256:1610a2a20e2e6edc88de59c552431c6c5f4c952f0b5f3860fd4bf36a84ba4bed                                                                                                                     0.0s
 => => extracting sha256:253f4d9d62d1dcde17221764cad8a6730a4e65caf09e086e53b9154ec95967f5                                                                                                                     0.8s
 => => extracting sha256:eb8a848ba9121c881d4cd0f77e97b58319b20058c83693d1a0d197b706d1a111                                                                                                                     6.6s
 => => extracting sha256:e5da18124cc8ae8db4caa90b5f052116fa68b6e058c717259cb5252d4addd046                                                                                                                     0.0s
 => => extracting sha256:515f8cd27a372807a993910898cdc309c80ba205e8085716d578257661e59074                                                                                                                     0.0s
 => => extracting sha256:84c35afd7ff237f4273e5c035d333058b4cd702425363abc1d8d013f5ac92727                                                                                                                     0.6s
 => => extracting sha256:aed635b11e9aa855e41fa90d660ff1a079d37e66edf02fff34606661856ea1dd                                                                                                                     0.0s
 => => extracting sha256:e5e90ebfb41ba0be3922b7e3696711cc410ec6533d1f91a7aebf65dc0efccb14                                                                                                                     0.0s
 => => extracting sha256:162c6388688c70f96d2b3682d1d2f21e72891283f1a38a78267d8533d51cd557    
=> [internal] load build context                                                                                                                                                                             0.0s
 => => transferring context: 14.01kB                                                                                                                                                                          0.0s
 => [ 2/17] RUN mkdir -p "/usr/games/.wine/drive_c/Program Files (x86)"                                                                                                                                       0.2s
 => [ 3/17] WORKDIR /usr/games                                                                                                                                                                                3.9s
 => [ 4/17] RUN wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip && unzip steamcmd.zip -d "/usr/games/.wine/drive_c/Program Files (x86)"/Steam && rm steamcmd.zip                           0.3s
 => [ 5/17] RUN wine "/usr/games/.wine/drive_c/Program Files (x86)"/Steam/steamcmd.exe +login "anonymous" "" "" +app_update "1829350" +quit 2> /dev/null ; exit 0                                            18.6s
 => [ 6/17] RUN ln -s "/usr/games/.wine/drive_c/Program Files (x86)"/Steam /usr/games/Steam                                                                                                                   0.4s 
 => [ 7/17] COPY files /usr/games/files                                                                                                                                                                       4.7s 
 => [ 8/17] RUN mkdir -p /usr/games/Steam/steamapps/common                                                                                                                                                    0.2s 
 => [ 9/17] RUN find /usr/games/Steam/steamapps/common -maxdepth 0 -not -name "Steamworks Shared" | xargs -I{} cp -rf files/* {} && rm -rf files                                                              0.4s 
 => [10/17] RUN chown -R games:games /usr/games                                                                                                                                                              27.5s 
 => [11/17] COPY init.d/game-server /etc/init.d/game-server                                                                                                                                                   0.0s 
 => [12/17] RUN update-rc.d game-server defaults && echo "HEADLESS=yes\nRUNCMD=$(cat <<EOL\n-persistentDataPath /usr/games/files\nEOL\n)" > .game-server                                                      0.4s
 => [13/17] RUN if [ "no" = yes ]; then usermod --password "$(openssl passwd -1 -salt $(openssl rand -base64 6) games)" --shell /bin/bash games; fi                                                           0.4s
 => [14/17] COPY config /usr/games/.config                                                                                                                                                                    4.3s
 => [15/17] RUN sed -i 's/allow_channels=true/allow_channels=false/g' /etc/xrdp/xrdp.ini                                                                                                                      0.2s
 => ERROR [16/17] RUN mv /usr/games/.config/user-dirs.conf /etc/xdg/user-dirs.defaults                                                                                                                        0.4s
------
 **> [16/17] RUN mv /usr/games/.config/user-dirs.conf /etc/xdg/user-dirs.defaults:
#0 0.391 mv: cannot move '/usr/games/.config/user-dirs.conf' to a subdirectory of itself, '/etc/xdg/user-dirs.defaults'**
------
Dockerfile:48
--------------------
  46 |     COPY config /usr/games/.config
  47 |     RUN sed -i 's/allow_channels=true/allow_channels=false/g' /etc/xrdp/xrdp.ini
  48 | >>> RUN mv /usr/games/.config/user-dirs.conf /etc/xdg/user-dirs.defaults
  49 |     
  50 |     COPY launch.sh /usr/games/launch.sh
--------------------
ERROR: failed to solve: process "/bin/sh -c mv /usr/games/.config/user-dirs.conf /etc/xdg/user-dirs.defaults" did not complete successfully: exit code: 1
```

**Comment by nuxy** [comment] 2023-05-18 23:17
@Magnacoder Running the command you provided (Ubuntu/Windows version) I'm not seeing the error:

```txt
$ docker build -t vrising-docker . --build-arg APPID=1829350 --build-arg RUNCMD='-persistentDataPath /usr/games/files'
Sending build context to Docker daemon   38.4kB
Step 1/31 : FROM scottyhardy/docker-wine
latest: Pulling from scottyhardy/docker-wine
ca1778b69356: Pull complete 
8142be1d7640: Pull complete 
2691a0c36c42: Pull complete 
f365d802bc44: Pull complete 
1610a2a20e2e: Pull complete 
253f4d9d62d1: Pull complete 
eb8a848ba912: Pull complete 
e5da18124cc8: Pull complete 
515f8cd27a37: Pull complete 
84c35afd7ff2: Pull complete 
aed635b11e9a: Pull complete 
e5e90ebfb41b: Pull complete 
162c6388688c: Pull complete 
Digest: sha256:d8e4475a7a58660221097be4bb6f886373fac94a360a2d4e1f5ab4d2b971d31e
Status: Downloaded newer image for scottyhardy/docker-wine:latest
 ---> 4c67ac859a6b
Step 2/31 : ARG USERNAME=anonymous
 ---> Running in 9a618bd7c56f
Removing intermediate container 9a618bd7c56f
 ---> 5ef28284f24f
Step 3/31 : ARG PASSWORD=
 ---> Running in ff979ab47d40
Removing intermediate container ff979ab47d40
 ---> e882d9e01d3c
Step 4/31 : ARG GUARDCODE=
 ---> Running in 6ec2ae92da73
Removing intermediate container 6ec2ae92da73
 ---> 86aba05a27da
Step 5/31 : ARG APPID=
 ---> Running in c757d78ff1f2
Removing intermediate container c757d78ff1f2
 ---> 323048137d18
Step 6/31 : ARG RUNCMD=
 ---> Running in 35c11cda6acf
Removing intermediate container 35c11cda6acf
 ---> cf26bfa01005
Step 7/31 : ARG HEADLESS=yes
 ---> Running in 12fcaf6fbac2
Removing intermediate container 12fcaf6fbac2
 ---> 4d40b8dfe760
Step 8/31 : ARG RDP_SERVER=no
 ---> Running in 4847a7ee56f1
Removing intermediate container 4847a7ee56f1
 ---> de0190db2aaa
Step 9/31 : ARG RDP_PASSWD=games
 ---> Running in e30f0fc7050e
Removing intermediate container e30f0fc7050e
 ---> 9183cc177160
Step 10/31 : ENV RDP_SERVER "$RDP_SERVER"
 ---> Running in fff8d7874d99
Removing intermediate container fff8d7874d99
 ---> c7bbd7bb526d
Step 11/31 : ENV DBUS_FATAL_WARNINGS 0
 ---> Running in 50d59490d27f
Removing intermediate container 50d59490d27f
 ---> 86d1ae2d996c
Step 12/31 : ENV WINEDEBUG -all
 ---> Running in 307b996f14f7
Removing intermediate container 307b996f14f7
 ---> a550575f6979
Step 13/31 : ENV WINEPREFIX /usr/games/.wine
 ---> Running in 84739e28c332
Removing intermediate container 84739e28c332
 ---> ca29e5545396
Step 14/31 : ENV PROGRAM_FILES "$WINEPREFIX"/drive_c/Program\ Files\ \(x86\)
 ---> Running in 8f51d965bfb3
Removing intermediate container 8f51d965bfb3
 ---> 5064721c24ae
Step 15/31 : RUN mkdir -p "$PROGRAM_FILES"
 ---> Running in 90fceee9e4c6
Removing intermediate container 90fceee9e4c6
 ---> 44f2fa3b465e
Step 16/31 : WORKDIR /usr/games
 ---> Running in c601aa63c9e0
Removing intermediate container c601aa63c9e0
 ---> 1b8ad1ef355a
Step 17/31 : RUN wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip && unzip steamcmd.zip -d "$PROGRAM_FILES"/Steam && rm steamcmd.zip
 ---> Running in 0eeeebe6afba
--2023-05-18 23:07:15--  https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip
Resolving steamcdn-a.akamaihd.net (steamcdn-a.akamaihd.net)... 23.48.174.98, 23.48.174.91
Connecting to steamcdn-a.akamaihd.net (steamcdn-a.akamaihd.net)|23.48.174.98|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 774825 (757K) [application/zip]
Saving to: ‘steamcmd.zip’

     0K .......... .......... .......... .......... ..........  6% 58.8M 0s
    50K .......... .......... .......... .......... .......... 13% 2.75M 0s
   100K .......... .......... .......... .......... .......... 19% 5.01M 0s
   150K .......... .......... .......... .......... .......... 26% 3.83M 0s
   200K .......... .......... .......... .......... .......... 33% 41.5M 0s
   250K .......... .......... .......... .......... .......... 39% 6.22M 0s
   300K .......... .......... .......... .......... .......... 46% 16.6M 0s
   350K .......... .......... .......... .......... .......... 52% 7.86M 0s
   400K .......... .......... .......... .......... .......... 59% 9.25M 0s
   450K .......... .......... .......... .......... .......... 66% 15.8M 0s
   500K .......... .......... .......... .......... .......... 72% 51.5M 0s
   550K .......... .......... .......... .......... .......... 79% 8.06M 0s
   600K .......... .......... .......... .......... .......... 85% 47.5M 0s
   650K .......... .......... .......... .......... .......... 92% 4.55M 0s
   700K .......... .......... .......... .......... .......... 99% 53.9M 0s
   750K ......                                                100% 35.8M=0.09s

2023-05-18 23:07:15 (8.45 MB/s) - ‘steamcmd.zip’ saved [774825/774825]

Archive:  steamcmd.zip
  inflating: /usr/games/.wine/drive_c/Program Files (x86)/Steam/steamcmd.exe  
Removing intermediate container 0eeeebe6afba
 ---> 03bc5be9c836
Step 18/31 : RUN wine "$PROGRAM_FILES"/Steam/steamcmd.exe +login "$USERNAME" "$PASSWORD" "$GUARDCODE" +app_update "$APPID" +quit 2> /dev/null ; exit 0
 ---> Running in a9f1b080d8a2
Steam Console Client (c) Valve Corporation - version 1682708339
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 0.00 (0 / 1563884649)
 Update state (0x61) downloading, progress: 1.98 (31005776 / 1563884649)
 Update state (0x61) downloading, progress: 9.96 (155786320 / 1563884649)
 Update state (0x61) downloading, progress: 20.71 (323835158 / 1563884649)
 Update state (0x61) downloading, progress: 30.85 (482483369 / 1563884649)
 Update state (0x61) downloading, progress: 43.53 (680755408 / 1563884649)
 Update state (0x61) downloading, progress: 58.79 (919403457 / 1563884649)
 Update state (0x61) downloading, progress: 72.87 (1139525138 / 1563884649)
 Update state (0x61) downloading, progress: 86.64 (1354989134 / 1563884649)
 Update state (0x61) downloading, progress: 89.13 (1393819970 / 1563884649)
 Update state (0x61) downloading, progress: 95.19 (1488633083 / 1563884649)
 Update state (0x61) downloading, progress: 100.00 (1563884649 / 1563884649)
 Update state (0x61) downloading, progress: 100.00 (1563884649 / 1563884649)
 Update state (0x81) verifying update, progress: 23.84 (372838862 / 1563884649)
 Update state (0x81) verifying update, progress: 49.04 (766893143 / 1563884649)
 Update state (0x81) verifying update, progress: 73.84 (1154700737 / 1563884649)
 Update state (0x81) verifying update, progress: 98.16 (1535089024 / 1563884649)
Success! App '1829350' fully installed.
Redirecting stderr to 'C:\Program Files (x86)\Steam\logs\stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Redirecting stderr to 'C:\Program Files (x86)\Steam\logs\stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
[  0%] Downloading update...
[  0%] Checking for available updates...
[----] Downloading update (196 of 43,352 KB)...
[  0%] Downloading update (3,113 of 43,352 KB)...
[  7%] Downloading update (7,098 of 43,352 KB)...
[ 16%] Downloading update (10,346 of 43,352 KB)...
[ 23%] Downloading update (12,867 of 43,352 KB)...
[ 29%] Downloading update (14,405 of 43,352 KB)...
[ 33%] Downloading update (15,815 of 43,352 KB)...
[ 36%] Downloading update (17,416 of 43,352 KB)...
[ 40%] Downloading update (19,168 of 43,352 KB)...
[ 44%] Downloading update (21,212 of 43,352 KB)...
[ 48%] Downloading update (23,368 of 43,352 KB)...
[ 53%] Downloading update (25,311 of 43,352 KB)...
[ 58%] Downloading update (27,885 of 43,352 KB)...
[ 64%] Downloading update (30,450 of 43,352 KB)...
[ 70%] Downloading update (33,434 of 43,352 KB)...
[ 77%] Downloading update (36,869 of 43,352 KB)...
[ 85%] Downloading update (40,660 of 43,352 KB)...
[ 93%] Downloading update (43,352 of 43,352 KB)...
[100%] Download complete.
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Failed to clean up after update, continuing...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
Redirecting stderr to 'C:\Program Files (x86)\Steam\logs\stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
[----] Downloading update (0 of 66,838 KB)...
[  0%] Downloading update (0 of 66,838 KB)...
[  0%] Downloading update (0 of 66,838 KB)...
[  0%] Downloading update (0 of 66,838 KB)...
[  0%] Downloading update (0 of 66,838 KB)...
[  0%] Downloading update (11 of 66,838 KB)...
[  0%] Downloading update (49 of 66,838 KB)...
[  0%] Downloading update (414 of 66,838 KB)...
[  0%] Downloading update (1,060 of 66,838 KB)...
[  1%] Downloading update (1,380 of 66,838 KB)...
[  2%] Downloading update (2,046 of 66,838 KB)...
[  3%] Downloading update (2,690 of 66,838 KB)...
[  4%] Downloading update (3,668 of 66,838 KB)...
[  5%] Downloading update (4,577 of 66,838 KB)...
[  6%] Downloading update (5,650 of 66,838 KB)...
[  8%] Downloading update (6,904 of 66,838 KB)...
[ 10%] Downloading update (8,214 of 66,838 KB)...
[ 12%] Downloading update (9,658 of 66,838 KB)...
[ 14%] Downloading update (11,467 of 66,838 KB)...
[ 17%] Downloading update (13,585 of 66,838 KB)...
[ 20%] Downloading update (15,531 of 66,838 KB)...
[ 23%] Downloading update (16,873 of 66,838 KB)...
[ 25%] Downloading update (18,499 of 66,838 KB)...
[ 27%] Downloading update (20,175 of 66,838 KB)...
[ 30%] Downloading update (21,961 of 66,838 KB)...
[ 32%] Downloading update (23,791 of 66,838 KB)...
[ 35%] Downloading update (26,107 of 66,838 KB)...
[ 39%] Downloading update (27,857 of 66,838 KB)...
[ 41%] Downloading update (28,485 of 66,838 KB)...
[ 42%] Downloading update (28,839 of 66,838 KB)...
[ 43%] Downloading update (29,948 of 66,838 KB)...
[ 44%] Downloading update (31,324 of 66,838 KB)...
[ 46%] Downloading update (32,702 of 66,838 KB)...
[ 48%] Downloading update (34,175 of 66,838 KB)...
[ 51%] Downloading update (35,538 of 66,838 KB)...
[ 53%] Downloading update (36,905 of 66,838 KB)...
[ 55%] Downloading update (38,139 of 66,838 KB)...
[ 57%] Downloading update (39,516 of 66,838 KB)...
[ 59%] Downloading update (40,839 of 66,838 KB)...
[ 61%] Downloading update (42,190 of 66,838 KB)...
[ 63%] Downloading update (43,630 of 66,838 KB)...
[ 65%] Downloading update (44,917 of 66,838 KB)...
[ 67%] Downloading update (46,030 of 66,838 KB)...
[ 68%] Downloading update (47,429 of 66,838 KB)...
[ 70%] Downloading update (48,714 of 66,838 KB)...
[ 72%] Downloading update (50,172 of 66,838 KB)...
[ 75%] Downloading update (51,492 of 66,838 KB)...
[ 77%] Downloading update (52,798 of 66,838 KB)...
[ 78%] Downloading update (53,188 of 66,838 KB)...
[ 79%] Downloading update (54,358 of 66,838 KB)...
[ 81%] Downloading update (55,709 of 66,838 KB)...
[ 83%] Downloading update (56,969 of 66,838 KB)...
[ 85%] Downloading update (58,266 of 66,838 KB)...
[ 87%] Downloading update (59,491 of 66,838 KB)...
[ 89%] Downloading update (60,942 of 66,838 KB)...
[ 91%] Downloading update (62,216 of 66,838 KB)...
[ 93%] Downloading update (63,481 of 66,838 KB)...
[ 94%] Downloading update (64,756 of 66,838 KB)...
[ 96%] Downloading update (66,082 of 66,838 KB)...
[ 98%] Downloading update (66,838 of 66,838 KB)...
[100%] Download Complete.
[----] Applying update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Failed to clear up temporary update files used for rollback, continuing anyway
[----] Cleaning up...
[----] Update complete, launching...
Removing intermediate container a9f1b080d8a2
 ---> 90545e10d563
Step 19/31 : RUN ln -s "$PROGRAM_FILES"/Steam /usr/games/Steam
 ---> Running in 944018072cb1
Removing intermediate container 944018072cb1
 ---> 643c50ec2901
Step 20/31 : COPY files /usr/games/files
 ---> 7f151a3bfe6e
Step 21/31 : RUN mkdir -p /usr/games/Steam/steamapps/common
 ---> Running in e789dfdd8033
Removing intermediate container e789dfdd8033
 ---> 3d3a19c645e8
Step 22/31 : RUN find /usr/games/Steam/steamapps/common -maxdepth 0 -not -name "Steamworks Shared" | xargs -I{} cp -rf files/* {} && rm -rf files
 ---> Running in 1d6930c52b86
Removing intermediate container 1d6930c52b86
 ---> bf84da1cb65c
Step 23/31 : RUN chown -R games:games /usr/games
 ---> Running in 0518aae26370
Removing intermediate container 0518aae26370
 ---> c0da93043c05
Step 24/31 : COPY init.d/game-server /etc/init.d/game-server
 ---> d8d5891e9af0
Step 25/31 : RUN update-rc.d game-server defaults && echo "HEADLESS=$HEADLESS\nRUNCMD=\$(cat <<EOL\n$RUNCMD\nEOL\n)" > .game-server
 ---> Running in f9c4fa6eea48
Removing intermediate container f9c4fa6eea48
 ---> a83ba11c4314
Step 26/31 : RUN if [ "$RDP_SERVER" = yes ]; then usermod --password "$(openssl passwd -1 -salt $(openssl rand -base64 6) $RDP_PASSWD)" --shell /bin/bash games; fi
 ---> Running in ef6ba072c337
Removing intermediate container ef6ba072c337
 ---> 8ae508318b2c
Step 27/31 : COPY config /usr/games/.config
 ---> 1ee907742284
Step 28/31 : RUN sed -i 's/allow_channels=true/allow_channels=false/g' /etc/xrdp/xrdp.ini
 ---> Running in 780c20c5bb2f
Removing intermediate container 780c20c5bb2f
 ---> f5c28810dae2
Step 29/31 : RUN mv /usr/games/.config/user-dirs.conf /etc/xdg/user-dirs.defaults
 ---> Running in d64308dca712
Removing intermediate container d64308dca712
 ---> 72450765cc68
Step 30/31 : COPY launch.sh /usr/games/launch.sh
 ---> d4c5f5bebb3c
Step 31/31 : ENTRYPOINT /usr/games/launch.sh
 ---> Running in 6cfb730b5674
Removing intermediate container 6cfb730b5674
 ---> 9a82e059470e
Successfully built 9a82e059470e
Successfully tagged vrising-docker:latest
 ```

**Questions for you about your set-up**

- Are you running this from a native OS (non-virtualized) or from within an existing Docker/LXC container?
- Are you using the Steam [Linux](https://github.com/nuxy/docker-steamcmd-wine/releases/tag/0.1.2) native or [Windows](https://github.com/nuxy/docker-steamcmd-wine/releases/tag/1.0.1) native release?

**Comment by nuxy** [comment] 2023-05-18 23:21
One last item..

What Docker version you are running?

```txt
$ docker -v
Docker version 19.03.13, build 4484c46d9d
```

**Comment by nuxy** [comment] 2023-05-21 17:40
Closing this issue since it's not reproducible when run in a non-virtualized/containerized context.

Re-open if you're still experiencing this with the details to the questions asked above.

**Closed as completed by nuxy** 2023-05-21 17:40 UTC
Labels: question
